import java.util.Arrays;
import java.util.stream.Stream;

/**
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

  /**
   * Greet
   *
   * @return String greeting Word
   */
  private String getGreeting() {
    return "Hello world.";
  }

  /**
   * Main　なんかする
   *
   * @param args String array
   */
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    if (args.length != 0) {
      System.out.println(args.length + " words were detected. \nPrint start. ");
      Stream.of(args).forEach(System.out::println);
    }

    // Sort
    //// Bubble sort
    //int[] numbers = {5, 4, 3, 2, 1};
    int[] numbers = {1, 2, 3, 4, 5};
    int swapCount = -1;
    int processCount = 0;
    int unsortedMaxIndex = numbers.length - 1;
    int swapTempInt = 0;

    while (swapCount != 0) {
      processCount++;
      swapCount = 0;

      for (int i = 0; i < unsortedMaxIndex; i++) {
        if (numbers[i] > numbers[i + 1]){
          swapTempInt = numbers[i];
          numbers[i] = numbers[i + 1];
          numbers[i + 1] = swapTempInt;
          swapCount++;
        }
      }
      unsortedMaxIndex--;

    }

    System.out.println(String.format("処理回数は%sです", processCount));
    System.out.println(String.format("ソート後の配列は%sです", Arrays.toString(numbers)));

  }

}
